# -*- coding: utf-8 -*-
"""big mart sales.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13JpSH53Ed9l59VE46d4ggSVSbYFgRvN3
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import warnings

from google.colab import files


uploaded = files.upload()

warnings.filterwarnings('ignore')
data = pd.read_csv('bigmart.csv')
data.sample(5)

"""Find Shape of Our Dataset (Number of Rows And Number of Columns)"""

data.shape

"""statistics of a data set"""

data.describe()

"""Check Null Values In The Dataset

in percentage of null values
"""

per = data.isnull().sum() * 100 / len(data)
print(per)

"""Taking Care of Duplicate Values"""

data.duplicated().any()

"""Handling The missing Values

"""

data['Item_Weight']

data['Outlet_Size']

"""Univariate Imputation"""

mean_weight = data['Item_Weight'].mean()
median_weight = data['Item_Weight'].median()
print(mean_weight,median_weight)

"""fill missing values with mean and median"""

data['Item_Weight_mean']=data['Item_Weight'].fillna(mean_weight)
data['Item_Weight_median']=data['Item_Weight'].fillna(median_weight)

data.head(1)

"""check variance after and before"""

print("Original Weight variable variance",data['Item_Weight'].var())
print("Item Weight variance after mean imputation",data['Item_Weight_mean'].var())
print("Item Weight variance after median imputation",data['Item_Weight_median'].var())

"""data distribution

Kernel Density Estimation (KDE) plots
"""

data['Item_Weight'].plot(kind = "kde",label="Original")

data['Item_Weight_mean'].plot(kind = "kde",label = "Mean")

data['Item_Weight_median'].plot(kind = "kde",label = "Median")

plt.legend()
plt.show()

"""box plot method"""

data[['Item_Weight','Item_Weight_mean','Item_Weight_median']].boxplot()

"""linear  interploate method"""

data['Item_Weight_interploate']=data['Item_Weight'].interpolate(method="linear")
data['Item_Weight'].plot(kind = "kde",label="Original")

data['Item_Weight_interploate'].plot(kind = "kde",label = "interploate")

plt.legend()
plt.show()

"""

```
# This is formatted as code
```

Multivariate imputation"""

#knn-k nearest neighbours plot for missing values
from sklearn.impute import KNNImputer
knn = KNNImputer(n_neighbors=10,weights="distance")
data['knn_imputer']= knn.fit_transform(data[['Item_Weight']]).ravel()
data['Item_Weight'].plot(kind = "kde",label="Original")

data['knn_imputer'].plot(kind = "kde",label = "KNN imputer")

plt.legend()
plt.show()

data = data.drop(['Item_Weight','Item_Weight_mean','Item_Weight_median','knn_imputer'],axis=1)

data.head(1)

data.isnull().sum()

"""Mode method to filling missing values in outlet_size column"""

data['Outlet_Size'].value_counts()

"""based on oulet_type filling missing values of outlet_size"""

data['Outlet_Type'].value_counts()

mode_outlet = data.pivot_table(values='Outlet_Size',columns='Outlet_Type',aggfunc=(lambda x:x.mode()[0]))

"""these are most frequently used"""

mode_outlet

missing_values = data['Outlet_Size'].isnull()

missing_values

data.loc[missing_values,'Outlet_Size'] = data.loc[missing_values,'Outlet_Type'].apply(lambda x :mode_outlet[x])

data.isnull().sum()

"""# **Item_Fat_Content**"""

data.columns

data['Item_Fat_Content'].value_counts()

"""to join all the same item_fat column"""

data.replace({'Item_Fat_Content':{'Low Fat':'LF','low fat':'LF','reg':'Regular'}},inplace=True)

data['Item_Fat_Content'].value_counts()

"""# **Item_Visibility**"""

data.columns

data['Item_Visibility'].value_counts()

"""handling to remove zeros using linear interploate"""

data['Item_Visibility_interpolate']=data['Item_Visibility'].replace(0,np.nan).interpolate(method='linear')

data.head(1)

data['Item_Visibility_interpolate'].value_counts()

data['Item_Visibility'].plot(kind="kde",label="Original")

data['Item_Visibility_interpolate'].plot(kind="kde",color='red',label="Interpolate")

plt.legend()
plt.show()

data = data.drop('Item_Visibility',axis=1)
data.head(1)

"""# **Item_Type**"""

data.columns

data['Item_Type'].value_counts()

"""# **Item_Identifier**

1.   List item
2.   List item



"""

data.columns

data['Item_Identifier'].value_counts().sample(5)

data['Item_Identifier'] =data['Item_Identifier'].apply(lambda x : x[:2])

data['Item_Identifier'].value_counts()

"""# **Outlet_Establishment_Year**

"""

data.columns

data['Outlet_Establishment_Year']

import datetime as dt

current_year = dt.datetime.today().year

current_year

"""Outlet_age-how many years the outlet is present"""

data['Outlet_age']= current_year - data['Outlet_Establishment_Year']

data.head(1)

data = data.drop('Outlet_Establishment_Year',axis=1)

data.head()

"""# **Handling Categorical Columns**

converting categorial column to numerical
"""

from sklearn.preprocessing import OrdinalEncoder

data_encoded = data.copy()

cat_cols = data.select_dtypes(include=['object']).columns

for col in cat_cols:
    oe = OrdinalEncoder()
    data_encoded[col]=oe.fit_transform(data_encoded[[col]])
    print(oe.categories_)

data_encoded.head(3)

X = data_encoded.drop('Item_Outlet_Sales',axis=1)
y = data_encoded['Item_Outlet_Sales']

y

"""# **Random Forest Regressor**"""

from sklearn.ensemble import RandomForestRegressor

from sklearn.model_selection import cross_val_score

rf = RandomForestRegressor(n_estimators=100,random_state=42)
scores = cross_val_score(rf,X,y,cv=5,scoring='r2')
print(scores.mean())

"""# **XGBRFRegressor**"""

from xgboost import XGBRFRegressor

xg = XGBRFRegressor(n_estimators=100,random_state=42)
scores = cross_val_score(xg,X,y,cv=5,scoring='r2')
print(scores.mean())

""":# XGBRFRegressor Feature importances"""

xg = XGBRFRegressor(n_estimators=100,random_state=42)

xg1 = xg.fit(X,y)
pd.DataFrame({
    'feature':X.columns,
    'XGBRF_importance':xg1.feature_importances_

}).sort_values(by='XGBRF_importance',ascending=False)

['Item_Visibility_interpolate','Item_Weight_interploate',
'Item_Type','Outlet_Location_Type','Item_Identifier','Item_Fat_Content']

from xgboost import XGBRFRegressor

xg = XGBRFRegressor(n_estimators=100,random_state=42)
scores = cross_val_score(xg1,X.drop(['Item_Visibility_interpolate','Item_Weight_interploate',
'Item_Type','Outlet_Location_Type','Item_Identifier','Item_Fat_Content'],axis=1),y,cv=5,scoring='r2')
print(scores.mean())

final_data = X.drop(columns=['Item_Visibility_interpolate','Item_Weight_interploate',
'Item_Type','Outlet_Location_Type','Item_Identifier','Item_Fat_Content'],axis=1)

final_data

"""# **Best Model**"""

from xgboost import XGBRFRegressor
xg_final = XGBRFRegressor()
xg_final.fit(final_data,y)

from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error

X_train,X_test,y_train,y_test = train_test_split(final_data,y, test_size=0.20, random_state=42)

xg_final.fit(X_train,y_train)

y_pred = xg_final.predict(X_test)

mean_absolute_error(y_test,y_pred)

"""# Prediction on Unseen Data"""

pred = xg_final.predict(np.array([[141.6180, 9.0, 1.0, 1.0, 24]]))[0]
print("Predicted Sales Value:", pred)

print(f"Sales Value is between {pred-714.42} and {pred+714.42}")

"""# Save Model Using Joblib

*   List item
*   List item


"""

import joblib

joblib.dump(xg_final,'Sales forecast')

model = joblib.load('Sales forecast')

pred = model.predict(np.array([[141.6180,9.0,1.0,1.0,24]]))[0]
print(pred)

print("Predicted Sales Value (Loaded Model):", pred)

"""# GUI"""

import numpy as np
import datetime as dt
import joblib
import ipywidgets as widgets
from IPython.display import display

current_year = dt.datetime.today().year

# ---------- Widgets ----------

# MRP as typing input
item_mrp = widgets.FloatText(
    description='Item MRP',
    placeholder='Enter MRP value'
)

# Outlet Identifier
outlet_identifier = widgets.Dropdown(
    options=['OUT010', 'OUT013', 'OUT017', 'OUT018', 'OUT019',
             'OUT027', 'OUT035', 'OUT045', 'OUT046', 'OUT049'],
    description='Outlet ID'
)

# Outlet Size
outlet_size = widgets.Dropdown(
    options=['High', 'Medium', 'Small'],
    description='Outlet Size'
)

# Outlet Type
outlet_type = widgets.Dropdown(
    options=['Grocery Store', 'Supermarket Type1',
             'Supermarket Type2', 'Supermarket Type3'],
    description='Outlet Type'
)

# Outlet Year Dropdown (1987–2013)
outlet_year = widgets.Dropdown(
    options=list(range(1987, 2014)),
    description='Outlet Year'
)

output = widgets.Output()

# ---------- Prediction Function ----------

def predict_sales(b):

    p1 = item_mrp.value

    outlet_map = {
        "OUT010": 0, "OUT013": 1, "OUT017": 2, "OUT018": 3, "OUT019": 4,
        "OUT027": 5, "OUT035": 6, "OUT045": 7, "OUT046": 8, "OUT049": 9
    }
    p2 = outlet_map[outlet_identifier.value]

    size_map = {"High": 0, "Medium": 1, "Small": 2}
    p3 = size_map[outlet_size.value]

    type_map = {
        "Grocery Store": 0,
        "Supermarket Type1": 1,
        "Supermarket Type2": 2,
        "Supermarket Type3": 3
    }
    p4 = type_map[outlet_type.value]

    # Outlet Age
    p5 = current_year - outlet_year.value

    # Load model
    model = joblib.load('Sales forecast')

    # Predict
    predicted_sales = model.predict(
        np.array([[p1, p2, p3, p4, p5]])
    )[0]

    # Business logic
    buffer_stock = predicted_sales * 0.10
    planned_stock = predicted_sales + buffer_stock

    with output:
        output.clear_output()
        print(f"Expected Sales Value: ₹{predicted_sales:.2f}")
        print(f"Recommended Planning Value (with 10% buffer): ₹{planned_stock:.2f}")

# ---------- Button ----------

button = widgets.Button(description="Predict Sales")
button.on_click(predict_sales)

# ---------- Display ----------

display(
    item_mrp,
    outlet_identifier,
    outlet_size,
    outlet_type,
    outlet_year,
    button,
    output
)